In [81]:
from window import *
from objects2d import *
import math

In [82]:
#Keyboard and Mouse Events Capture
boolScale = 0
s_x = 1.0
s_y = 1.0
t_x = 0.0
t_y = 0.0
theta = 0
def key_event(window,key,scancode,action,mods):
    global t_x, t_y
    global s_x, s_y
    global boolScale
#     print('[key event] key=',key)
#     print('[key event] scancode=',scancode)
#     print('[key event] action=',action)
#     print('[key event] mods=',mods)
#     print('-------')
    if key == 262: #right
        t_x += 0.01
    elif key == 263: #left
        t_x -= 0.01
    if key == 264: #down
        t_y -= 0.01
    elif key == 265: #up
        t_y += 0.01
    if key == 68: # D
        s_x += 0.01
    elif key == 65: # A
        s_x -= 0.01
    if key == 83: # S
        s_y -= 0.01
    elif key == 87: # W
        s_y += 0.01
        
    elif key == 77: # M
        boolScale = True
    

def mouse_event(window,button,action,mods):
    global theta
    #print('[mouse event] button=',button)
    #print('[mouse event] action=',action)
    #print('[mouse event] mods=',mods)
    #print('-------')
    if button == 0:
        theta -= 0.01
    elif button == 1:
        theta += 0.01

In [83]:
def getCircleCoordinates(n_vertices, radius, center = (0, 0)):
    '''
    Get coordinates to draw a circle.
    Parameters
    ----------
        n_vertices : int
            Number of vertices that will be used to draw the circle.
        radius : float
            Radius of circle
        center : (float, float)
            Center of circle
    Return
    ------
        vertices
            Vertices with coordinates to draw the circle
    '''
    
    pi = 3.14
    angle = 0.0
    vertices = []
    
    for counter in range(n_vertices):
        angle += 2*pi/n_vertices
        x = center[0] + math.cos(angle) * radius
        y = center[1] + math.sin(angle) * radius
        vertices.append((x,y))
    
    return vertices

In [84]:
def setColor(loc_color, color):
    glUniform4f(loc_color, color[0], color[1], color[2], color[3])

In [85]:
def multiply_matrix(a,b):
    m_a = a.reshape(4,4)
    m_b = b.reshape(4,4)
    m_c = np.dot(m_a,m_b)
    c = m_c.reshape(1,16)
    return c

In [86]:
# Colors's Normalized RGB
red    = (1.0  , 0    , 0    , 1.0)
blue   = (0    , 0    , 1.0  , 1.0)
yellow = (1.0  , 0.96 , 0    , 1.0)
purple = (0.749, 0    , 1.0  , 1.0)
orange = (1.0  , 0.658, 0    , 1.0)
green  = (0.282, 0.737, 0.184, 1.0)
black  = (0    , 0    , 0    , 1.0)
gray   = (0.858, 0.858, 0.858, 1.0)
dark_gray = (0.424, 0.424, 0.424, 1.0)
white  = (1.0  , 1.0  , 1.0  , 1.0)

In [87]:
# Montagem de cenário

mat_bat_body = np.array([-0.539533 ,  -0.0124742 ,  0.   ,       0.04   ,     0.02245356 ,-0.29974055,
   0.  ,        0.02    ,    0.    ,      0.    ,      1.  ,        0.,
   0.    ,      0.   ,       0.  ,        1.        ], np.float32)

mat_bat_head = np.array([0.18, 0. ,  0. ,  0.05, 0. , 0.18, 0.,   0.04, 0.,   0.  , 1. ,  0. ,  0. ,  0.,
  0. ,  1.  ], np.float32)

mat_bat_leftear = np.array([0.04, 0. ,  0.  , 0.02 ,0.  , 0.16, 0. ,  0.14, 0.  , 0.,   1.,   0.,   0.,   0.,
  0. ,  1.  ], np.float32)


mat_bat_rightear = np.array([0.05, 0.,   0. ,  0.08, 0. ,  0.2,  0. ,  0.14, 0. ,  0. ,  1. ,  0. ,  0. ,  0.,
  0.  , 1.  ], np.float32)

mat_witch_hat2 = np.array([ 0.09928086, -0.0323223 ,  0.    ,     -0.04   ,     0.01197122,  0.26805833,
   0.   ,       0.18    ,    0.     ,     0.   ,       1.  ,        0.,
   0.     ,     0.   ,       0.   ,       1.        ], np.float32)
mat_witch_face = np.array([ 0.18,  0.,    0. ,  -0.02 , 0.  ,  0.19,  0.  ,  0.,    0. ,   0. ,   1.,    0.,
   0. ,   0.  ,  0. ,   1.  ], np.float32)

In [88]:
# Coordinates
coord = []

# aux = [
#             ( 0.5, -0.5),
#             ( -0.5, -0.5),
#             ( 0.0, 0.0)
#                             ]

# for i in range (3):
#     teste = np.dot(mat_bat_rightear.reshape(4,4), np.array(aux[i]+ (0,1)))
#     print(teste)

#0
coord_aux = getCircleCoordinates(32, 0.3) #Função de pegar circulo com seus parâmetros (Coloca a sua)
coord_mult = []
for x in range (len(coord_aux)):
    mult = np.dot(mat_bat_body.reshape(4,4), np.array(coord_aux[x]+ (0,1))) #Sua multiplicação de matriz aqui
    
    coord_mult.append((mult[0], mult[1]))
coord += coord_mult


#32
coord_aux = getCircleCoordinates(32, 0.3) #Função de pegar circulo com seus parâmetros (Coloca a sua)
coord_mult = []
for x in range (len(coord_aux)):
    mult = np.dot(mat_bat_head.reshape(4,4), np.array(coord_aux[x]+ (0,1))) #Sua multiplicação de matriz aqui
    
    coord_mult.append((mult[0], mult[1]))
coord += coord_mult


# 64
coord += [
            ( 0.04, 0.06),
            ( 0. ,  0.06),
            ( 0.02 ,0.14)
                            ]

# 67
coord += [
            ( 0.105, 0.04),
            ( 0.055, 0.04),
            ( 0.08, 0.14)
                            ]




In [89]:
window, program, loc_color = initWindow("The Witch's Night", coord, key_event, mouse_event, 1000, 1000)

In [90]:
while not glfw.window_should_close(window):

    glfw.poll_events()
    
    
    if(boolScale == True):
        s_x += 0.02
        s_y += 0.02
    
    if(s_x > 20):
#         s_x = 1
#         s_y = 1
        boolScale = False
        
    if(boolScale == False and s_x > 1):
        s_x -= 0.02
        s_y -= 0.02
    
    glClear(GL_COLOR_BUFFER_BIT) 
    glClearColor(1.0, 1.0, 1.0, 1.0)
    mat_scaling = np.array([          s_x, 0.0, 0.0, 0.0, 
                                      0.0, s_y, 0.0, 0.0, 
                                      0.0, 0.0, 1.0, 0.0, 
                                      0.0, 0.0, 0.0, 1.0], np.float32)
      
    mat_translation = np.array([    1.0, 0.0, 0.0, t_x, 
                                    0.0, 1.0, 0.0, t_y, 
                                    0.0, 0.0, 1.0, 0.0, 
                                    0.0, 0.0, 0.0, 1.0], np.float32)
    
    mat_translation2 = np.array([   0.0, 0.0, 0.0, t_x, 
                                    0.0, 0.0, 0.0, t_y, 
                                    0.0, 0.0, 0.0, 0.0, 
                                    0.0, 0.0, 0.0, 0.0], np.float32)
    
    mat_i = np.array([              1.0, 0.0, 0.0, 0.0, 
                                    0.0, 1.0, 0.0, 0.0, 
                                    0.0, 0.0, 1.0, 0.0, 
                                    0.0, 0.0, 0.0, 1.0], np.float32) 


    mat_rotation = np.array([       math.cos(theta), -math.sin(theta), 0.0, 0.0, 
                                    math.sin(theta),  math.cos(theta), 0.0, 0.0, 
                                    0.0,              0.0,             1.0, 0.0, 
                                    0.0,              0.0,             0.0, 1.0], np.float32)

    loc = glGetUniformLocation(program, "mat_transformation")

    #   FACE
    mat_transformation = multiply_matrix(mat_i, mat_scaling)
    glUniformMatrix4fv(loc, 1, GL_TRUE, mat_transformation)
    setColor(loc_color, black)
    draw_circles(0, 16) 
    
    mat_transformation = multiply_matrix(mat_i, mat_scaling)
    glUniformMatrix4fv(loc, 1, GL_TRUE, mat_transformation)
    setColor(loc_color, black)
    draw_circles(32, 32) 
    
    mat_transformation = multiply_matrix(mat_i, mat_scaling)
    glUniformMatrix4fv(loc, 1, GL_TRUE, mat_transformation)
    setColor(loc_color, black)
    draw_triangles(64)  
    
    mat_transformation = multiply_matrix(mat_i, mat_scaling)
    glUniformMatrix4fv(loc, 1, GL_TRUE, mat_transformation)
    setColor(loc_color, black)
    draw_triangles(67)  
    
    print(mat_transformation)
    # mat_transformation = multiply_matrix(multiply_matrix(mat_translation, mat_rotation), mat_scaling)
    
    glfw.swap_buffers(window)

glfw.terminate()

[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0

[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0

[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
[[1.02 0.   0.   0.   0.   1.02 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[1.04 0.   0.   0.   0.   1.04 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[1.06 0.   0.   0.   0.   1.06 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[1.08 0.   0.   0. 

  0.   1.  ]]
[[6.1 0.  0.  0.  0.  6.1 0.  0.  0.  0.  1.  0.  0.  0.  0.  1. ]]
[[6.12 0.   0.   0.   0.   6.12 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.14 0.   0.   0.   0.   6.14 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.16 0.   0.   0.   0.   6.16 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.18 0.   0.   0.   0.   6.18 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.2 0.  0.  0.  0.  6.2 0.  0.  0.  0.  1.  0.  0.  0.  0.  1. ]]
[[6.22 0.   0.   0.   0.   6.22 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.24 0.   0.   0.   0.   6.24 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.26 0.   0.   0.   0.   6.26 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.28 0.   0.   0.   0.   6.28 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.3 0.  0.  0.  0.  6.3 0.  0.  0.  0.  1.  0.  0.  0.  0.  1. ]]
[[6.32 0.   0.   0.   0.   6.32 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[6.34 0.   0.   0.   0.  

   0.    0.    0.    1.  ]]
[[12.54  0.    0.    0.    0.   12.54  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.56  0.    0.    0.    0.   12.56  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.58  0.    0.    0.    0.   12.58  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.6  0.   0.   0.   0.  12.6  0.   0.   0.   0.   1.   0.   0.   0.
   0.   1. ]]
[[12.62  0.    0.    0.    0.   12.62  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.64  0.    0.    0.    0.   12.64  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.66  0.    0.    0.    0.   12.66  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.68  0.    0.    0.    0.   12.68  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[12.7  0.   0.   0.   0.  12.7  0.   0.   0.   0.   1.   0.   0.   0.
   0.   1. ]]
[[12.72  0.    0.    0.    0.   12.72  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[

   0.   1. ]]
[[19.32  0.    0.    0.    0.   19.32  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.34  0.    0.    0.    0.   19.34  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.36  0.    0.    0.    0.   19.36  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.38  0.    0.    0.    0.   19.38  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.4  0.   0.   0.   0.  19.4  0.   0.   0.   0.   1.   0.   0.   0.
   0.   1. ]]
[[19.42  0.    0.    0.    0.   19.42  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.44  0.    0.    0.    0.   19.44  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.46  0.    0.    0.    0.   19.46  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.48  0.    0.    0.    0.   19.48  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[19.5  0.   0.   0.   0.  19.5  0.   0.   0.   0.   1.   0.   0.   0.
   0.   1. ]]
[[19.52  0.    0

   0.   1. ]]
[[14.08  0.    0.    0.    0.   14.08  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[14.06  0.    0.    0.    0.   14.06  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[14.04  0.    0.    0.    0.   14.04  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[14.02  0.    0.    0.    0.   14.02  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[14.  0.  0.  0.  0. 14.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.]]
[[13.98  0.    0.    0.    0.   13.98  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[13.96  0.    0.    0.    0.   13.96  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[13.94  0.    0.    0.    0.   13.94  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[13.92  0.    0.    0.    0.   13.92  0.    0.    0.    0.    1.    0.
   0.    0.    0.    1.  ]]
[[13.9  0.   0.   0.   0.  13.9  0.   0.   0.   0.   1.   0.   0.   0.
   0.   1. ]]
[[13.88  0.    0.    0.    0.   1

[[7.5 0.  0.  0.  0.  7.5 0.  0.  0.  0.  1.  0.  0.  0.  0.  1. ]]
[[7.48 0.   0.   0.   0.   7.48 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.46 0.   0.   0.   0.   7.46 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.44 0.   0.   0.   0.   7.44 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.42 0.   0.   0.   0.   7.42 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.4 0.  0.  0.  0.  7.4 0.  0.  0.  0.  1.  0.  0.  0.  0.  1. ]]
[[7.38 0.   0.   0.   0.   7.38 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.36 0.   0.   0.   0.   7.36 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.34 0.   0.   0.   0.   7.34 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.32 0.   0.   0.   0.   7.32 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.3 0.  0.  0.  0.  7.3 0.  0.  0.  0.  1.  0.  0.  0.  0.  1. ]]
[[7.28 0.   0.   0.   0.   7.28 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[7.26 0.   0.   0.   0.   7.26 0.   0. 

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.  

  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   0.   0.
  0.   1.  ]]
[[0.98 0.   0.   0.   0.   0.98 0.   0.   0.   0.   1.   0.   